language: python

jobs:
  include:
    - python: '3.6'
      env: TARGET=test
    - python: '3.7'
      env: TARGET=test
    - python: '3.8'
      env: TARGET=test

services:
  - docker

before_install:
  - docker run --rm -itd -p 5555:5555 rigetti/quilc -R -P
  - docker run --rm -itd -p 5000:5000 rigetti/qvm -S

install:
  - make requirements

script:
  - make $TARGET
